apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  type: NodePort
  selector:
    app: restaurant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
